name: Hosted deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    environment: prod

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Clever login & deploy
        run: |
          clever login --token ${{ secrets.CC_TOKEN }} --secret ${{ secrets.CC_SECRET }} 
          clever deploy --force || clever restart 
